import type { Dictionary } from "./types";

export const de: Dictionary = {
  meta: {
    title: "Rechtsanwältin Meral Gören – Kanzlei in Mannheim | Deutsch & Türkisch",
    description:
      "Rechtsanwaltskanzlei Meral Gören, Mannheim: Allgemeines Zivilrecht, Arbeitsrecht, Ausländerrecht, Familienrecht und Verkehrsrecht. Beratung auf Deutsch und Türkisch.",
    locale: "de_DE",
  },
  cta: "Beratung anfragen",
  menuLabel: "Menü",
  navLabel: "Hauptnavigation",
  languageLabel: "Sprache",
  nav: {
    home: "Startseite",
    about: "Über mich",
    areas: "Rechtsgebiete",
    blog: "Blog",
    contact: "Kontakt",
  },
  hero: {
    label: "Rechtsanwältin Meral Gören · Mannheim",
    title: {
      lead: "Verlässliche Beratung für",
      accent: "Ihre nächste Entscheidung.",
    },
    text: "Auf Deutsch und Türkisch, im Zivil-, Arbeits-, Ausländer-, Familien- und Verkehrsrecht. Sie erfahren, wo Sie stehen – und was als Nächstes zu tun ist.",
    whatsapp: "Per WhatsApp schreiben",
  },
  areas: {
    label: "Rechtsgebiete",
    title: "Fünf Schwerpunkte. Eine Ansprechpartnerin.",
    text: "Ich vertrete Sie in fünf Rechtsgebieten – persönlich, verständlich und in beiden Sprachen.",
    more: "Mehr erfahren",
    moreTo: "Mehr erfahren zu",
    items: [
      {
        slug: "zivilrecht",
        num: "01",
        title: "Allgemeines Zivilrecht",
        text: "Verträge, Forderungen, Kaufrecht, Mietrecht, Schadensersatz.",
        lead: "Verträge, Forderungen und Streitigkeiten zwischen Privatpersonen oder mit Unternehmen.",
        topics: [
          "Vertragsprüfung und -gestaltung",
          "Forderungen und Mahnverfahren",
          "Kaufrecht und Gewährleistung",
          "Mietrecht",
          "Schadensersatz",
          "Außergerichtliche Einigung",
        ],
        how: "Ich prüfe Ihre Unterlagen, bewerte Chancen und Kosten und vertrete Sie außergerichtlich oder vor Gericht.",
      },
      {
        slug: "arbeitsrecht",
        num: "02",
        title: "Arbeitsrecht",
        text: "Kündigung, Abmahnung, Arbeitsvertrag, Lohn- und Urlaubsansprüche.",
        lead: "Vom Kündigungsschutz bis zur Abrechnung – arbeitsrechtliche Fragen haben meist kurze Fristen.",
        topics: [
          "Kündigungsschutzklage",
          "Abmahnung",
          "Arbeitsvertrag und Aufhebungsvertrag",
          "Lohn- und Urlaubsansprüche",
          "Arbeitszeugnis",
          "Betriebsbedingte Kündigung",
        ],
        how: "Bei einer Kündigung gilt: Die Klagefrist beträgt drei Wochen ab Zugang. Wir prüfen zuerst die Frist, dann die Wirksamkeit – und klären, ob Weiterbeschäftigung oder Abfindung Ihr Ziel ist.",
      },
      {
        slug: "auslaenderrecht",
        num: "03",
        title: "Ausländerrecht",
        text: "Aufenthaltstitel, Einbürgerung, Familiennachzug, Niederlassungserlaubnis.",
        lead: "Aufenthalt, Einbürgerung und Familiennachzug – Verfahren, die von Fristen und vollständigen Unterlagen leben.",
        topics: [
          "Aufenthaltstitel und Verlängerung",
          "Einbürgerung",
          "Familiennachzug",
          "Visum und Niederlassungserlaubnis",
          "Ausweisung und Abschiebung",
          "Verpflichtungserklärung",
        ],
        how: "Wir klären zuerst Ihren Status und die Zuständigkeiten, stellen die Unterlagen vollständig zusammen und begleiten Sie gegenüber der Ausländerbehörde – auf Deutsch und auf Türkisch.",
      },
      {
        slug: "familienrecht",
        num: "04",
        title: "Familienrecht",
        text: "Scheidung, Unterhalt, Sorge- und Umgangsrecht, Ehevertrag.",
        lead: "Trennung, Scheidung, Unterhalt und Kinder – mit Blick auf deutsches und türkisches Recht, wo beides eine Rolle spielt.",
        topics: [
          "Scheidung",
          "Trennungs- und Kindesunterhalt",
          "Sorge- und Umgangsrecht",
          "Zugewinn und Vermögensaufteilung",
          "Ehevertrag",
          "Anerkennung ausländischer Entscheidungen",
        ],
        how: "Familienrechtliche Verfahren brauchen Ruhe und klare Schritte. Wir klären zuerst, welches Recht anwendbar ist, dann das Vorgehen.",
      },
      {
        slug: "verkehrsrecht",
        num: "05",
        title: "Verkehrsrecht",
        text: "Bußgeld, Fahrverbot, Unfallregulierung und Schadensersatz.",
        lead: "Nach einem Unfall oder einem Bußgeldbescheid entscheidet oft, wie schnell reagiert wird.",
        topics: [
          "Bußgeldbescheid und Punkte",
          "Fahrverbot und Fahrerlaubnis",
          "Unfallregulierung",
          "Schadensersatz und Schmerzensgeld",
          "Streit mit der Kfz-Versicherung",
          "Verkehrsstrafrecht",
        ],
        how: "Gegen einen Bußgeldbescheid haben Sie nur zwei Wochen Zeit für den Einspruch. Nach einem Unfall prüfe ich Haftung, Gutachten und das Angebot der Versicherung, bevor Sie etwas unterschreiben.",
      },
    ],
  },
  about: {
    label: "Über mich",
    title: "Zwei Sprachen. Zwei Rechtskulturen.",
    p1: "Ich bin Meral Gören, Rechtsanwältin in Mannheim. Ich berate auf Deutsch und Türkisch und kenne die Fragen, die entstehen, wenn Lebenswege zwischen Deutschland und der Türkei verlaufen.",
    p2: "Sie sprechen mit mir – nicht mit einer Sachbearbeitung. Jeder Fall wird von mir persönlich geführt, von der ersten Einschätzung bis zum Abschluss.",
    background:
      "Nach einem langjährigen Jurastudium und dem Referendariat am Landgericht – mit Stationen bei Gericht, Staatsanwaltschaft, Behörden und in mehreren Kanzleien – berate ich in allen rechtlichen Fragen. Meine Schwerpunkte liegen im allgemeinen Zivilrecht, Arbeitsrecht, Ausländerrecht, Familienrecht und Verkehrsrecht.",
    cta: "Kontakt aufnehmen",
  },
  why: {
    label: "Was Sie erwartet",
    title: "Warum Sie uns vertrauen können",
    items: [
      {
        title: "Deutsch und Türkisch",
        text: "Beratung und Schriftverkehr in beiden Sprachen – ohne Dolmetscher.",
      },
      {
        title: "Persönliche Bearbeitung",
        text: "Ihr Fall bleibt bei mir – von der Erstberatung bis zum Abschluss.",
      },
      {
        title: "Kanzlei in Mannheim",
        text: "R1 2,3, mitten in den Quadraten. Termine vor Ort oder telefonisch.",
      },
      {
        title: "Klare Kommunikation",
        text: "Verständliche Einschätzung, transparente Kosten, kein Fachjargon ohne Erklärung.",
      },
    ],
  },
  blog: {
    label: "Blog",
    title: "Aktuelle Beiträge",
    all: "Alle Beiträge",
    more: "Weiterlesen",
    moreTo: "Weiterlesen:",
    posts: [
      {
        slug: "mietminderung-maengel",
        category: "Zivilrecht",
        iso: "2026-09-02",
        date: "2. September 2026",
        title: "Mietminderung: Wann Sie die Miete kürzen dürfen",
        excerpt:
          "Schimmel, Heizungsausfall, Baulärm – wann ein Mangel zur Minderung berechtigt und was Sie vorher erledigen müssen.",
        body: [
          "Ist die Wohnung mangelhaft, ist die Miete kraft Gesetzes gemindert (§ 536 BGB). Das ist ein wichtiger Unterschied zu vielen anderen Rechten: Sie müssen die Minderung nicht erst erklären, sie tritt automatisch ein. Voraussetzung ist ein Mangel, der die Tauglichkeit der Wohnung zum vertragsgemäßen Gebrauch nicht nur unerheblich beeinträchtigt.",
          "Typische Fälle sind Schimmel, ein Heizungsausfall in der Heizperiode, undichte Fenster, Wasserschäden oder länger andauernder Baulärm. Auch Umstände außerhalb der Wohnung können einen Mangel begründen, wenn sie das Wohnen spürbar beeinträchtigen.",
          "Zwingend ist die Mängelanzeige. Nach § 536c BGB müssen Sie den Mangel unverzüglich anzeigen. Unterlassen Sie das, verlieren Sie Ansprüche und können sich unter Umständen sogar schadensersatzpflichtig machen. Zeigen Sie den Mangel deshalb schriftlich an, beschreiben Sie ihn konkret und setzen Sie eine angemessene Frist zur Beseitigung.",
          "Sichern Sie parallel die Beweise: Fotos mit Datum, ein Protokoll mit Uhrzeiten und Dauer der Störung – bei Lärm ein Lärmprotokoll –, Zeugen sowie den gesamten Schriftverkehr. Im Streit entscheidet regelmäßig, wer den Mangel und sein Ausmaß belegen kann.",
          "Die Höhe der Minderung richtet sich nach der tatsächlichen Beeinträchtigung. Die kursierenden Minderungstabellen geben allenfalls eine grobe Orientierung; Gerichte entscheiden im Einzelfall. Hier liegt das eigentliche Risiko: Wer zu viel mindert, gerät in Zahlungsrückstand – und bei einem Rückstand von zwei Monatsmieten kann der Vermieter fristlos kündigen (§ 543 Abs. 2 Nr. 3 BGB).",
          "Der sichere Weg ist deshalb, die Miete zunächst in voller Höhe ausdrücklich unter Vorbehalt der Rückforderung weiterzuzahlen und den geminderten Betrag anschließend zurückzuverlangen. Sie behalten damit Ihre Ansprüche, riskieren aber keine Kündigung.",
          "Kein Minderungsrecht besteht, wenn Sie den Mangel bei Vertragsschluss kannten (§ 536b BGB) oder ihn selbst verursacht haben. Auch deshalb lohnt es sich, den Zustand der Wohnung bei der Übergabe sorgfältig zu protokollieren.",
        ],
        image: "/images/post-tenancy.jpg",
      },
      {
        slug: "einbuergerung-2026",
        category: "Ausländerrecht",
        iso: "2026-08-12",
        date: "12. August 2026",
        title: "Einbürgerung 2026: Welche Voraussetzungen jetzt gelten",
        excerpt:
          "Aufenthaltsdauer, Sprachnachweis, Lebensunterhalt – ein Überblick über die aktuellen Anforderungen.",
        body: [
          "Seit der Reform des Staatsangehörigkeitsrechts vom 27. Juni 2024 ist die Einbürgerung in der Regel schon nach fünf Jahren rechtmäßigem gewöhnlichem Aufenthalt möglich – zuvor waren es acht. Ebenso wichtig: Die bisherige Staatsangehörigkeit muss grundsätzlich nicht mehr aufgegeben werden. Für viele, die den Antrag jahrelang aufgeschoben haben, hat sich die Rechnung damit verändert.",
          "Die Voraussetzungen im Überblick: ein gültiger Aufenthaltstitel beziehungsweise ein Daueraufenthaltsrecht, fünf Jahre rechtmäßiger gewöhnlicher Aufenthalt in Deutschland, ein gesicherter Lebensunterhalt, Deutschkenntnisse auf dem Niveau B1, der bestandene Einbürgerungstest, keine relevanten Vorstrafen und ein Bekenntnis zur freiheitlichen demokratischen Grundordnung.",
          "Der Lebensunterhalt ist in der Praxis der häufigste Stolperstein. Sie müssen den Unterhalt für sich und Ihre unterhaltsberechtigten Angehörigen grundsätzlich ohne Leistungen nach dem SGB II oder SGB XII bestreiten können. Von diesem Grundsatz gibt es eng gefasste Ausnahmen – etwa für Angehörige der ehemaligen Gastarbeitergeneration oder für Menschen, die in Vollzeit erwerbstätig sind. Ob eine dieser Ausnahmen greift, sollten Sie prüfen lassen, bevor Sie den Antrag zurückstellen.",
          "Beim Sprachnachweis genügt in der Regel ein Zertifikat auf dem Niveau B1 oder ein deutscher Schulabschluss. Für Fälle von Alter, Krankheit oder Behinderung sieht das Gesetz Erleichterungen vor.",
          "Neu ist seit der Reform außerdem ein ausdrückliches Bekenntnis zum Schutz der Menschenwürde und zur besonderen historischen Verantwortung Deutschlands. Antisemitisch, rassistisch oder sonst menschenverachtend motivierte Taten schließen die Einbürgerung aus.",
          "Die Regelungen zur beschleunigten Einbürgerung bei besonderen Integrationsleistungen sind seit 2024 mehrfach Gegenstand gesetzlicher Änderungen gewesen. Bevor Sie Ihre Planung darauf stützen, lassen Sie den aktuellen Stand für Ihren Fall prüfen.",
          "Was Sie jetzt zusammenstellen sollten: den lückenlosen Nachweis Ihrer Aufenthaltszeiten und -titel, Einkommensnachweise der letzten Monate, den Rentenverlauf, das Sprachzertifikat, die Bescheinigung über den Einbürgerungstest und Ihre Identitätsdokumente. Lücken in der Aufenthaltshistorie sind der häufigste Grund für Verzögerungen – und sie lassen sich fast immer schließen, wenn man früh damit beginnt.",
        ],
        image: "/images/post-1.jpg",
      },
      {
        slug: "kuendigung-drei-wochen",
        category: "Arbeitsrecht",
        iso: "2026-07-28",
        date: "28. Juli 2026",
        title: "Kündigung erhalten – die ersten drei Wochen entscheiden",
        excerpt:
          "Warum die Frist für die Kündigungsschutzklage so wichtig ist und was Sie sofort tun sollten.",
        body: [
          "Wenn Sie eine Kündigung erhalten, läuft ab dem Zugang eine Frist von drei Wochen. Innerhalb dieser Frist muss die Kündigungsschutzklage beim Arbeitsgericht eingegangen sein (§ 4 KSchG). Versäumen Sie die Frist, gilt die Kündigung nach § 7 KSchG als von Anfang an wirksam – unabhängig davon, wie angreifbar sie inhaltlich gewesen wäre.",
          "Entscheidend ist der Zugang, nicht das Datum auf dem Schreiben. Bei einem Einwurf in den Briefkasten kommt es auf den Tag an, an dem üblicherweise mit der Leerung zu rechnen ist. Notieren Sie deshalb sofort, wann und auf welchem Weg Sie die Kündigung erhalten haben, und heben Sie den Umschlag auf.",
          "Die Frist gilt auch dann, wenn die Kündigung offensichtlich unwirksam erscheint – etwa weil sie nicht eigenhändig unterschrieben ist, von einer nicht vertretungsberechtigten Person stammt oder ein Sonderkündigungsschutz wegen Schwangerschaft, Elternzeit oder Schwerbehinderung übergangen wurde. Auch diese Einwände müssen innerhalb der drei Wochen erhoben werden.",
          "Nur ausnahmsweise lässt § 5 KSchG eine nachträgliche Zulassung der Klage zu, wenn Sie trotz aller zumutbaren Sorgfalt gehindert waren, rechtzeitig zu klagen. Darauf sollte niemand seine Planung stützen.",
          "Unabhängig von der Klage gilt: Melden Sie sich spätestens drei Tage nach Kenntnis der Kündigung bei der Agentur für Arbeit arbeitsuchend (§ 38 SGB III), sonst droht eine Minderung des Arbeitslosengeldes. Und unterschreiben Sie nichts vorschnell – ein Aufhebungs- oder Abwicklungsvertrag kann eine Sperrzeit auslösen und nimmt Ihnen zugleich die Verhandlungsposition.",
          "Ob am Ende die Weiterbeschäftigung, eine Abfindung oder ein verbessertes Zeugnis steht, entscheidet sich meist im Gütetermin, der häufig schon wenige Wochen nach Klageeingang stattfindet. Die drei Wochen sind der Zugang zu dieser Verhandlung. Deshalb ist der frühe Anruf wichtiger als die perfekt vorbereitete Akte.",
        ],
        image: "/images/post-2.jpg",
      },
      {
        slug: "scheidung-tuerkei",
        category: "Familienrecht",
        iso: "2026-07-09",
        date: "9. Juli 2026",
        title: "Scheidung mit Bezug zur Türkei: Welches Recht gilt?",
        excerpt: "Deutsches oder türkisches Familienrecht – wovon die Antwort abhängt.",
        body: [
          "Wenn Eheleute Bezüge zu Deutschland und zur Türkei haben, sind zwei Fragen sauber zu trennen: Welches Gericht ist zuständig – und welches Recht wendet dieses Gericht an? Die Antworten fallen nicht zwingend zusammen. Ein deutsches Gericht kann türkisches Recht anwenden, und umgekehrt.",
          "Die internationale Zuständigkeit deutscher Gerichte richtet sich nach der Brüssel-IIb-Verordnung. Sie knüpft vor allem an den gewöhnlichen Aufenthalt an: Leben beide Eheleute in Deutschland, sind deutsche Gerichte zuständig – auch dann, wenn beide ausschließlich die türkische Staatsangehörigkeit besitzen.",
          "Welches Recht anzuwenden ist, bestimmt die Rom-III-Verordnung. Sie gilt auch im Verhältnis zu Staaten, die selbst nicht beteiligt sind; die Türkei gehört dazu. Maßgeblich ist in erster Linie der gewöhnliche Aufenthalt der Eheleute zum Zeitpunkt der Anrufung des Gerichts. Leben beide in Deutschland, wird in der Regel deutsches Scheidungsrecht angewendet.",
          "Wichtig ist die Möglichkeit der Rechtswahl: Die Eheleute können in notarieller Form vereinbaren, welches Recht auf die Scheidung anwendbar sein soll – etwa türkisches Recht. Das kann sinnvoll sein, wirkt sich aber nicht auf alle Folgesachen aus. Unterhalt, Versorgungsausgleich und Güterrecht folgen jeweils eigenen Kollisionsregeln.",
          "Eine in der Türkei ausgesprochene Scheidung wird in Deutschland nicht automatisch anerkannt. Erforderlich ist grundsätzlich ein Anerkennungsverfahren bei der zuständigen Landesjustizverwaltung (§ 107 FamFG). Ohne diese Anerkennung gelten Sie in Deutschland weiterhin als verheiratet – mit allen Folgen für eine erneute Eheschließung, das Erbrecht und das Melderecht.",
          "Umgekehrt muss eine deutsche Scheidung in der Türkei registriert werden, damit sie dort im Personenstandsregister nachvollzogen wird. Beides sollte man von Beginn an mitdenken: Wer nur eines der beiden Verfahren betreibt, hat am Ende einen Personenstand, der in einem der beiden Länder nicht stimmt.",
          "Für die Beratung heißt das: Zuerst klären wir Zuständigkeit und anwendbares Recht, dann die Folgesachen, dann die Anerkennung auf der jeweils anderen Seite. In dieser Reihenfolge lassen sich die meisten späteren Überraschungen vermeiden.",
        ],
        image: "/images/post-3.jpg",
      },
    ],
  },
  contact: {
    label: "Kontakt",
    title: "Beratung anfragen",
    text: "Beschreiben Sie kurz Ihr Anliegen. Ich melde mich zeitnah bei Ihnen.",
    name: "Name",
    email: "E-Mail",
    phone: "Telefon (optional)",
    area: "Rechtsgebiet",
    areaPlaceholder: "Bitte wählen",
    message: "Nachricht",
    consentA: "Ich habe die",
    consentLink: "Datenschutzerklärung",
    consentB:
      "gelesen und stimme der Verarbeitung meiner Daten zur Bearbeitung meiner Anfrage zu.",
    submit: "Anfrage senden",
    sending: "Wird gesendet…",
    error: "Senden fehlgeschlagen. Bitte versuchen Sie es erneut oder rufen Sie an.",
    addressLabel: "Adresse",
    country: "Deutschland",
    phoneLabel: "Telefon",
    whatsapp: "WhatsApp öffnen",
    hoursLabel: "Öffnungszeiten",
    hours: "Mo–Fr: [Platzhalter: Zeiten]",
    hoursNote: "Termine nach Vereinbarung.",
  },
  footer: {
    blurb: "Rechtsberatung auf Deutsch und Türkisch in Mannheim.",
    navTitle: "Navigation",
    areasTitle: "Rechtsgebiete",
    contactTitle: "Kontakt",
    imprint: "Impressum",
    privacy: "Datenschutz",
    copyright: "© 2026 Rechtsanwaltskanzlei Meral Gören",
    callLink: "Anrufen",
    waLink: "WhatsApp",
    formLink: "Kontaktformular",
    route: "Anfahrt",
  },
  partner: {
    label: "Kooperation",
    title: "Türkisches Recht, geregelt von Mannheim aus.",
    text: "Scheidungen, Erbfälle und Urteile berühren oft zwei Rechtsordnungen zugleich. Für alles, was türkischem Recht unterliegt, arbeite ich mit der Doğru Kanzlei zusammen. So bleibt Ihre Sache in einer Hand, und Sie müssen dafür nicht in die Türkei reisen.",
    firm: "Doğru Kanzlei",
    person: "Avukat Hasan Doğru",
    bio: "Zugelassen bei der Anwaltskammer Ankara und nach § 207 BRAO bei der Rechtsanwaltskammer Karlsruhe. Beim Amtsgericht Mannheim als Sachverständiger für türkisches Recht gelistet.",
    locationsLabel: "Standorte",
    locations: "Mannheim · Ankara",
    languagesLabel: "Sprachen",
    languages: "Türkçe · Deutsch · English",
    areasLabel: "Womit er Sie unterstützt",
    areas: [
      "Anerkennung deutscher Urteile in der Türkei",
      "Scheidung und Familiensachen",
      "Erbfälle und Nachlass in der Türkei",
      "Strafverfahren in der Türkei",
      "Vollmachten und Apostille",
    ],
    cta: "Zur Doğru Kanzlei",
  },
  cookie: {
    title: "Cookies & Datenschutz",
    text: "Diese Website verwendet technisch notwendige Cookies. Optionale Cookies für Statistik setzen wir nur mit Ihrer Einwilligung (§ 25 TDDDG, Art. 6 DSGVO).",
    acceptAll: "Alle akzeptieren",
    necessaryOnly: "Nur notwendige",
    customize: "Anpassen",
    save: "Auswahl speichern",
    necessary: "Notwendig",
    necessaryText: "Für den Betrieb der Seite erforderlich.",
    stats: "Statistik",
    statsText: "Anonyme Nutzungsstatistik zur Verbesserung der Seite.",
  },
  page: {
    home: "Startseite",
    more: "Weiterlesen",
    allPosts: "Alle Beiträge",
    backHome: "Zur Startseite",
    areaEyebrow: "Rechtsgebiete",
    areaTopics: "Typische Anliegen",
    areaHow: "So arbeite ich",
    areaAside: "Beschreiben Sie kurz Ihr Anliegen – auf Deutsch oder Türkisch.",
    otherAreas: "Weitere Rechtsgebiete",
    postDisclaimer:
      "Dieser Beitrag gibt einen allgemeinen Überblick und ersetzt keine Beratung im Einzelfall. Maßgeblich ist die Rechtslage zum Zeitpunkt Ihres Anliegens.",
    legalNote:
      "Alle in eckigen Klammern markierten Angaben sind Platzhalter und müssen vor Veröffentlichung von der Mandantin ergänzt bzw. juristisch geprüft werden.",
    blog: {
      eyebrow: "Blog",
      title: "Beiträge",
      lead: "Kurz und verständlich: aktuelle Fragen aus Zivil-, Arbeits-, Ausländer-, Familien- und Verkehrsrecht.",
    },
    danke: {
      eyebrow: "Kontakt",
      title: "Danke für Ihre Anfrage",
      lead: "Ihre Nachricht ist eingegangen.",
      body: "Ich melde mich zeitnah bei Ihnen – per E-Mail oder telefonisch, je nachdem, was Sie angegeben haben.",
      urgent: "In dringenden Fällen erreichen Sie mich unter",
    },
    impressum: {
      eyebrow: "Rechtliches",
      title: "Impressum",
      lead: "Angaben gemäß § 5 DDG.",
      sections: [
        {
          heading: "Anbieterin",
          paragraphs: [
            "Rechtsanwaltskanzlei Meral Gören\nRechtsanwältin Meral Gören\nR1 2,3\n68161 Mannheim\nDeutschland",
          ],
        },
        {
          heading: "Kontakt",
          paragraphs: ["Telefon: +49 176 31186560\nE-Mail: [Platzhalter: E-Mail-Adresse]"],
        },
        {
          heading: "Berufsbezeichnung und Kammer",
          paragraphs: [
            "Berufsbezeichnung: Rechtsanwältin (verliehen in der Bundesrepublik Deutschland)\nZuständige Kammer: [Platzhalter: Rechtsanwaltskammer]",
          ],
        },
        {
          heading: "Berufsrechtliche Regelungen",
          paragraphs: [
            "Bundesrechtsanwaltsordnung (BRAO), Berufsordnung für Rechtsanwälte (BORA), Fachanwaltsordnung (FAO), Rechtsanwaltsvergütungsgesetz (RVG), Berufsregeln der Rechtsanwälte der Europäischen Union (CCBE). Einsehbar unter www.brak.de.",
          ],
        },
        {
          heading: "Berufshaftpflichtversicherung",
          paragraphs: ["[Platzhalter: Versicherer, Anschrift, räumlicher Geltungsbereich]"],
        },
        {
          heading: "Umsatzsteuer-ID",
          paragraphs: ["[Platzhalter: USt-IdNr. gemäß § 27a UStG]"],
        },
        {
          heading: "Streitbeilegung",
          paragraphs: [
            "Die Europäische Kommission stellt eine Plattform zur Online-Streitbeilegung bereit: https://ec.europa.eu/consumers/odr. Zur Teilnahme an einem Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle: [Platzhalter: bereit/nicht bereit].",
          ],
        },
      ],
    },
    datenschutz: {
      eyebrow: "Rechtliches",
      title: "Datenschutzerklärung",
      lead: "Informationen zur Verarbeitung personenbezogener Daten nach Art. 13 DSGVO.",
      sections: [
        {
          heading: "1. Verantwortliche",
          paragraphs: [
            "Rechtsanwältin Meral Gören, R1 2,3, 68161 Mannheim, Telefon +49 176 31186560, E-Mail [Platzhalter].",
          ],
        },
        {
          heading: "2. Hosting und Server-Logfiles",
          paragraphs: [
            "Beim Aufruf der Website verarbeitet der Hoster [Platzhalter: Hoster] automatisch IP-Adresse, Zeitpunkt, aufgerufene Seite, Browser. Rechtsgrundlage: Art. 6 Abs. 1 lit. f DSGVO (sicherer Betrieb).",
          ],
        },
        {
          heading: "3. Kontaktformular und E-Mail",
          paragraphs: [
            "Angaben aus dem Kontaktformular (Name, E-Mail, Telefon, Rechtsgebiet, Nachricht) werden zur Bearbeitung Ihrer Anfrage verarbeitet und per E-Mail an die Kanzlei übermittelt. Rechtsgrundlage: Art. 6 Abs. 1 lit. b DSGVO sowie Ihre Einwilligung (lit. a). Löschung nach Abschluss der Anfrage, soweit keine Mandatierung erfolgt und keine Aufbewahrungspflichten bestehen.",
          ],
        },
        {
          heading: "4. WhatsApp",
          paragraphs: [
            "Wenn Sie über WhatsApp Kontakt aufnehmen, verarbeitet WhatsApp Ireland Ltd. Ihre Daten nach eigenen Bestimmungen. Bitte übermitteln Sie keine vertraulichen Mandatsinhalte über WhatsApp.",
          ],
        },
        {
          heading: "5. Cookies",
          paragraphs: [
            "Technisch notwendige Cookies werden auf Grundlage von § 25 Abs. 2 TDDDG gesetzt. Optionale Statistik-Cookies nur mit Ihrer Einwilligung (§ 25 Abs. 1 TDDDG, Art. 6 Abs. 1 lit. a DSGVO). Ihre Auswahl können Sie jederzeit über das Cookie-Banner ändern. [Platzhalter: eingesetzte Dienste]",
          ],
        },
        {
          heading: "6. Ihre Rechte",
          paragraphs: [
            "Sie haben das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit und Widerspruch (Art. 15–21 DSGVO) sowie auf Beschwerde bei einer Aufsichtsbehörde, z. B. dem Landesbeauftragten für den Datenschutz Baden-Württemberg.",
          ],
        },
      ],
    },
  },
};
