import type { Dictionary } from "./types";

export const tr: Dictionary = {
  meta: {
    title: "Avukat Meral Gören – Mannheim | Almanca & Türkçe",
    description:
      "Mannheim'da Avukat Meral Gören: Genel medeni hukuk, iş hukuku, yabancılar hukuku, aile hukuku ve trafik hukuku. Almanca ve Türkçe hukuki danışmanlık.",
    locale: "tr_TR",
  },
  cta: "Danışmanlık talep et",
  menuLabel: "Menü",
  navLabel: "Ana menü",
  languageLabel: "Dil",
  nav: {
    home: "Ana Sayfa",
    about: "Hakkımda",
    areas: "Hukuk Alanları",
    blog: "Blog",
    contact: "İletişim",
  },
  hero: {
    label: "Avukat Meral Gören · Mannheim",
    title: {
      lead: "Bir sonraki adımınız için",
      accent: "güvenilir danışmanlık.",
    },
    text: "Almanca ve Türkçe; medeni, iş, yabancılar, aile ve trafik hukukunda. Nerede durduğunuzu ve sırada ne olduğunu öğrenirsiniz.",
    whatsapp: "WhatsApp'tan yazın",
  },
  areas: {
    label: "Hukuk Alanları",
    title: "Beş uzmanlık alanı. Tek muhatap.",
    text: "Sizi beş hukuk alanında temsil ediyorum – kişisel, anlaşılır ve iki dilde.",
    more: "Daha fazla bilgi",
    moreTo: "Daha fazla bilgi:",
    items: [
      {
        slug: "zivilrecht",
        num: "01",
        title: "Genel Medeni Hukuk",
        text: "Sözleşmeler, alacaklar, satış hukuku, kira hukuku, tazminat.",
        lead: "Kişiler arası veya şirketlerle sözleşmeler, alacaklar ve uyuşmazlıklar.",
        topics: [
          "Sözleşme incelemesi ve hazırlanması",
          "Alacak ve ihtarname",
          "Satış hukuku ve ayıp",
          "Kira hukuku",
          "Tazminat",
          "Sulh görüşmeleri",
        ],
        how: "Belgelerinizi inceler, olasılık ve masrafları değerlendirir, sizi mahkeme dışında veya mahkemede temsil ederim.",
      },
      {
        slug: "arbeitsrecht",
        num: "02",
        title: "İş Hukuku",
        text: "Fesih, ihtar, iş sözleşmesi, ücret ve izin alacakları.",
        lead: "İşe iadeden hesaplaşmaya – iş hukuku sorunlarında süreler genellikle kısadır.",
        topics: [
          "İşe iade davası",
          "İhtar",
          "İş sözleşmesi ve ikale",
          "Ücret ve izin alacakları",
          "Bonservis",
          "İşletmesel nedenle fesih",
        ],
        how: "Fesihte dava süresi, bildirimin ulaşmasından itibaren üç haftadır. Önce süreyi, sonra geçerliliği inceleriz – ve hedefinizin işe iade mi yoksa tazminat mı olduğunu netleştiririz.",
      },
      {
        slug: "auslaenderrecht",
        num: "03",
        title: "Yabancılar Hukuku",
        text: "Oturma izni, vatandaşlık, aile birleşimi, süresiz oturma izni.",
        lead: "Oturma, vatandaşlık ve aile birleşimi – süreler ve eksiksiz belgelerle yürüyen süreçler.",
        topics: [
          "Oturma izni ve uzatma",
          "Vatandaşlık",
          "Aile birleşimi",
          "Vize ve süresiz oturma izni",
          "Sınır dışı ve ihraç",
          "Taahhütname",
        ],
        how: "Önce statünüzü ve yetkili makamları netleştirir, belgeleri eksiksiz hazırlar ve yabancılar dairesi nezdinde size eşlik ederim – Almanca ve Türkçe.",
      },
      {
        slug: "familienrecht",
        num: "04",
        title: "Aile Hukuku",
        text: "Boşanma, nafaka, velayet ve kişisel ilişki kurma hakkı, evlilik sözleşmesi.",
        lead: "Ayrılık, boşanma, nafaka ve çocuklar – gerektiğinde Alman ve Türk hukuku birlikte değerlendirilir.",
        topics: [
          "Boşanma",
          "Ayrılık ve çocuk nafakası",
          "Velayet ve kişisel ilişki",
          "Edinilmiş mal ve mal paylaşımı",
          "Evlilik sözleşmesi",
          "Yabancı kararların tanınması",
        ],
        how: "Aile davaları sakinlik ve net adımlar gerektirir. Önce hangi hukukun uygulanacağını, sonra yolu netleştiririz.",
      },
      {
        slug: "verkehrsrecht",
        num: "05",
        title: "Trafik Hukuku",
        text: "İdari para cezası, sürüş yasağı, kaza tasfiyesi ve tazminat.",
        lead: "Bir kazadan veya para cezası kararından sonra çoğu zaman ne kadar hızlı hareket edildiği belirleyicidir.",
        topics: [
          "Para cezası kararı ve ceza puanı",
          "Sürüş yasağı ve ehliyet",
          "Kaza tasfiyesi",
          "Maddi ve manevi tazminat",
          "Sigortayla uyuşmazlık",
          "Trafik ceza hukuku",
        ],
        how: "Para cezası kararına itiraz için yalnızca iki haftanız var. Kazadan sonra, siz bir şey imzalamadan önce sorumluluğu, ekspertiz raporunu ve sigortanın teklifini incelerim.",
      },
    ],
  },
  about: {
    label: "Hakkımda",
    title: "İki dil. İki hukuk kültürü.",
    p1: "Ben Meral Gören, Mannheim'da avukatım. Almanca ve Türkçe danışmanlık veriyorum ve Almanya ile Türkiye arasında geçen hayatların hukuki sorularını yakından tanıyorum.",
    p2: "Doğrudan benimle görüşürsünüz. Her dosya, ilk değerlendirmeden sonuca kadar bizzat tarafımdan yürütülür.",
    background:
      "Uzun bir hukuk öğrenimi ve eyalet mahkemesindeki avukatlık stajının ardından – mahkeme, savcılık, kamu kurumları ve çeşitli hukuk bürolarındaki istasyonlarla – her hukuki konuda danışmanlık veriyorum. Ağırlık noktalarım genel medeni hukuk, iş hukuku, yabancılar hukuku, aile hukuku ve trafik hukukudur.",
    cta: "İletişime geçin",
  },
  why: {
    label: "Sizi ne bekliyor",
    title: "Bize neden güvenebilirsiniz",
    items: [
      {
        title: "Almanca ve Türkçe",
        text: "Görüşmeler ve yazışmalar iki dilde – tercümansız.",
      },
      {
        title: "Kişisel takip",
        text: "Dosyanız ilk görüşmeden sonuca kadar bende kalır.",
      },
      {
        title: "Mannheim'da büro",
        text: "R1 2,3, şehir merkezinde. Yüz yüze veya telefonla randevu.",
      },
      {
        title: "Açık iletişim",
        text: "Anlaşılır değerlendirme, şeffaf ücretler, açıklamasız hukuk jargonu yok.",
      },
    ],
  },
  blog: {
    label: "Blog",
    title: "Güncel Yazılar",
    all: "Tüm yazılar",
    more: "Devamını oku",
    moreTo: "Devamını oku:",
    posts: [
      {
        slug: "mietminderung-maengel",
        category: "Medeni Hukuk",
        iso: "2026-09-02",
        date: "2 Eylül 2026",
        title: "Kira indirimi: Kirayı hangi durumlarda azaltabilirsiniz?",
        excerpt:
          "Küf, kombi arızası, inşaat gürültüsü – hangi ayıp indirim hakkı verir ve öncesinde ne yapmanız gerekir.",
        body: [
          "Konutta ayıp varsa kira bedeli kanun gereği kendiliğinden azalır (§ 536 BGB). Bu, diğer birçok haktan önemli bir farktır: İndirimi ayrıca beyan etmeniz gerekmez, kendiliğinden gerçekleşir. Koşul, konutun sözleşmeye uygun kullanıma elverişliliğini önemsiz olmayan ölçüde bozan bir ayıbın bulunmasıdır.",
          "Tipik örnekler: küf, ısıtma döneminde kombi veya kalorifer arızası, sızdıran pencereler, su hasarı ya da uzun süren inşaat gürültüsü. Konut dışındaki koşullar da oturmayı hissedilir biçimde bozuyorsa ayıp oluşturabilir.",
          "Ayıp bildirimi zorunludur. § 536c BGB uyarınca ayıbı gecikmeksizin bildirmeniz gerekir. Bildirmezseniz haklarınızı yitirirsiniz ve duruma göre tazminat sorumluluğu dahi doğabilir. Bu nedenle ayıbı yazılı olarak bildirin, somut biçimde tarif edin ve giderilmesi için uygun bir süre verin.",
          "Aynı anda delilleri de güvence altına alın: tarihli fotoğraflar, rahatsızlığın saatlerini ve süresini gösteren bir tutanak – gürültüde bir gürültü günlüğü –, tanıklar ve tüm yazışmalar. Uyuşmazlıkta çoğu kez ayıbı ve boyutunu kimin ispatlayabildiği belirleyici olur.",
          "İndirimin oranı fiilî bozulmaya göre belirlenir. Dolaşımdaki indirim tabloları olsa olsa kaba bir yön gösterir; mahkemeler somut olaya göre karar verir. Asıl risk burada: Fazla indirim yapan kişi ödeme gecikmesine düşer – iki aylık kira tutarında birikmiş borçta ev sahibi haklı nedenle derhâl feshedebilir (§ 543 f. 2 b. 3 BGB).",
          "Bu nedenle güvenli yol, kirayı önce tam olarak ve açıkça iade talebi saklı kalmak kaydıyla ödemeye devam etmek, indirilen tutarı sonrasında geri istemektir. Böylece haklarınızı korur, ancak fesih riskine girmezsiniz.",
          "Ayıbı sözleşmenin kurulduğu sırada biliyorsanız (§ 536b BGB) veya ayıba kendiniz sebep olduysanız indirim hakkı doğmaz. Konutun teslim sırasındaki durumunu özenle tutanağa bağlamak da bu yüzden değerlidir.",
        ],
        image: "/images/post-tenancy.jpg",
      },
      {
        slug: "einbuergerung-2026",
        category: "Yabancılar Hukuku",
        iso: "2026-08-12",
        date: "12 Ağustos 2026",
        title: "2026'da vatandaşlık: Güncel koşullar",
        excerpt: "İkamet süresi, dil belgesi, geçim – güncel şartlara genel bakış.",
        body: [
          "27 Haziran 2024 tarihli vatandaşlık hukuku reformundan bu yana vatandaşlık, kural olarak sekiz yıl yerine beş yıllık hukuka uygun mutat ikametten sonra mümkün. En az onun kadar önemlisi: Mevcut vatandaşlığın artık kural olarak bırakılması gerekmiyor. Başvuruyu yıllarca erteleyenler için hesap böylece değişti.",
          "Koşullara genel bakış: geçerli bir oturma izni ya da süresiz oturma hakkı, Almanya'da beş yıllık hukuka uygun mutat ikamet, güvence altına alınmış geçim, B1 düzeyinde Almanca, başarıyla geçilmiş vatandaşlık testi, ilgili bir sabıka kaydının bulunmaması ve özgür demokratik temel düzene bağlılık beyanı.",
          "Uygulamada en sık takılınan nokta geçimdir. Kendinizin ve bakmakla yükümlü olduğunuz yakınlarınızın geçimini kural olarak SGB II veya SGB XII yardımları olmadan sağlayabilmeniz gerekir. Bu kuralın dar kapsamlı istisnaları vardır – örneğin eski misafir işçi kuşağına mensup olanlar ya da tam zamanlı çalışanlar için. Başvuruyu ertelemeden önce bu istisnalardan birinin sizin için geçerli olup olmadığını incelettirin.",
          "Dil belgesinde kural olarak B1 düzeyinde bir sertifika veya bir Alman okul diploması yeterlidir. Yaş, hastalık veya engellilik hâllerinde kanun kolaylıklar öngörür.",
          "Reformla birlikte ayrıca insan onurunun korunmasına ve Almanya'nın özel tarihsel sorumluluğuna ilişkin açık bir bağlılık beyanı geldi. Antisemitik, ırkçı veya insan onurunu başka biçimde çiğneyen saiklerle işlenen fiiller vatandaşlığa engeldir.",
          "Özel uyum başarıları hâlinde hızlandırılmış vatandaşlığa ilişkin düzenlemeler 2024'ten bu yana birden çok kez yasal değişikliğe konu oldu. Planınızı buna dayandırmadan önce kendi durumunuz için güncel hukuki durumu incelettirin.",
          "Şimdiden hazırlamanız gerekenler: ikamet sürelerinizin ve izinlerinizin kesintisiz belgesi, son aylara ait gelir belgeleri, emeklilik hizmet dökümü, dil sertifikası, vatandaşlık testi belgesi ve kimlik belgeleriniz. İkamet geçmişindeki boşluklar gecikmelerin en sık nedenidir – ve erken başlanırsa neredeyse her zaman kapatılabilir.",
        ],
        image: "/images/post-1.jpg",
      },
      {
        slug: "kuendigung-drei-wochen",
        category: "İş Hukuku",
        iso: "2026-07-28",
        date: "28 Temmuz 2026",
        title: "Fesih bildirimi aldınız – ilk üç hafta belirleyici",
        excerpt: "İşe iade davası süresi neden bu kadar önemli ve hemen ne yapmalısınız.",
        body: [
          "Bir fesih bildirimi aldığınızda, bildirimin size ulaşmasından itibaren üç haftalık bir süre işlemeye başlar. Bu süre içinde işe iade davasının iş mahkemesine ulaşmış olması gerekir (§ 4 KSchG). Süreyi kaçırırsanız, fesih § 7 KSchG uyarınca baştan itibaren geçerli sayılır – içerik olarak ne kadar sakat olursa olsun.",
          "Belirleyici olan bildirimin size ulaşması, yazının üzerindeki tarih değil. Posta kutusuna bırakma hâlinde, kutunun olağan olarak boşaltılacağı gün esas alınır. Bu nedenle feshi ne zaman ve hangi yolla aldığınızı hemen not edin ve zarfı saklayın.",
          "Süre, fesih açıkça geçersiz görünse bile işler – örneğin ıslak imza taşımıyorsa, temsil yetkisi olmayan bir kişiden geliyorsa ya da gebelik, ebeveyn izni veya ağır engellilik nedeniyle özel fesih koruması göz ardı edilmişse. Bu itirazların da üç hafta içinde ileri sürülmesi gerekir.",
          "§ 5 KSchG yalnızca istisnaen, kendinizden beklenen tüm özeni göstermenize rağmen zamanında dava açmanız engellenmişse davanın sonradan kabulüne izin verir. Hiç kimse planını buna dayandırmamalı.",
          "Davadan bağımsız olarak: Fesihten haberdar olduktan en geç üç gün içinde İş Kurumu'na iş arayan olarak başvurun (§ 38 SGB III); aksi hâlde işsizlik ödeneğinde kesinti riski doğar. Ve aceleyle hiçbir şey imzalamayın – ikale veya tasfiye sözleşmesi bekleme süresi (Sperrzeit) doğurabilir ve aynı zamanda pazarlık gücünüzü elinizden alır.",
          "Sonuçta işe iadenin mi, bir tazminatın mı yoksa iyileştirilmiş bir bonservisin mi çıkacağı çoğu kez, dava açıldıktan birkaç hafta sonra yapılan uzlaşma duruşmasında belli olur. Üç hafta, bu duruşmaya açılan kapıdır. Bu yüzden erken yapılan telefon, kusursuz hazırlanmış bir dosyadan daha önemlidir.",
        ],
        image: "/images/post-2.jpg",
      },
      {
        slug: "scheidung-tuerkei",
        category: "Aile Hukuku",
        iso: "2026-07-09",
        date: "9 Temmuz 2026",
        title: "Türkiye bağlantılı boşanma: Hangi hukuk uygulanır?",
        excerpt: "Alman mı Türk aile hukuku mu – cevap neye bağlı.",
        body: [
          "Eşlerin hem Almanya hem Türkiye ile bağlantısı varsa iki soruyu net biçimde ayırmak gerekir: Hangi mahkeme yetkilidir – ve bu mahkeme hangi hukuku uygular? Cevaplar zorunlu olarak örtüşmez. Bir Alman mahkemesi Türk hukukunu uygulayabilir, tersi de mümkündür.",
          "Alman mahkemelerinin milletlerarası yetkisi Brüksel IIb Tüzüğü'ne göre belirlenir. Tüzük öncelikle mutat meskeni esas alır: Her iki eş de Almanya'da yaşıyorsa, ikisi de yalnızca Türk vatandaşı olsa dahi Alman mahkemeleri yetkilidir.",
          "Hangi hukukun uygulanacağını Roma III Tüzüğü belirler. Tüzük, kendisine taraf olmayan devletlerle ilişkide de uygulanır; Türkiye bunlardandır. Öncelikle eşlerin mahkemeye başvuru anındaki mutat meskeni esas alınır. İkisi de Almanya'da yaşıyorsa kural olarak Alman boşanma hukuku uygulanır.",
          "Hukuk seçimi imkânı önemlidir: Eşler noter huzurunda, boşanmaya hangi hukukun uygulanacağını – örneğin Türk hukukunu – kararlaştırabilir. Bu yerinde olabilir, ancak tüm fer'î sonuçları kapsamaz. Nafaka, emeklilik haklarının denkleştirilmesi ve mal rejimi kendi kanunlar ihtilafı kurallarına tabidir.",
          "Türkiye'de verilen bir boşanma kararı Almanya'da kendiliğinden tanınmaz. Kural olarak yetkili eyalet adalet idaresi nezdinde bir tanıma prosedürü gerekir (§ 107 FamFG). Bu tanıma olmadan Almanya'da hâlâ evli sayılırsınız – yeniden evlenme, miras hukuku ve nüfus kaydı bakımından tüm sonuçlarıyla birlikte.",
          "Bunun tersi de geçerli: Alman boşanma kararının Türkiye'de nüfus siciline işlenmesi için tescil ettirilmesi gerekir. Her ikisi de en baştan düşünülmeli. Yalnızca bir prosedürü yürüten kişi, sonunda iki ülkeden birinde doğru olmayan bir medeni hâle sahip olur.",
          "Danışmanlık açısından bu şu demek: Önce yetki ve uygulanacak hukuku, sonra fer'î sonuçları, ardından karşı taraftaki tanımayı netleştiririz. Bu sıra izlendiğinde sonraki sürprizlerin çoğu önlenebilir.",
        ],
        image: "/images/post-3.jpg",
      },
    ],
  },
  contact: {
    label: "İletişim",
    title: "Danışmanlık talep edin",
    text: "Konunuzu kısaca açıklayın. En kısa sürede size dönüş yaparım.",
    name: "Ad Soyad",
    email: "E-posta",
    phone: "Telefon (isteğe bağlı)",
    area: "Hukuk alanı",
    areaPlaceholder: "Lütfen seçin",
    message: "Mesaj",
    consentA: "",
    consentLink: "Gizlilik politikasını",
    consentB:
      "okudum ve talebimin işlenmesi için verilerimin kullanılmasını kabul ediyorum.",
    submit: "Talebi gönder",
    sending: "Gönderiliyor…",
    error: "Gönderim başarısız oldu. Lütfen tekrar deneyin veya telefonla ulaşın.",
    addressLabel: "Adres",
    country: "Almanya",
    phoneLabel: "Telefon",
    whatsapp: "WhatsApp'ı aç",
    hoursLabel: "Çalışma saatleri",
    hours: "Pzt–Cum: [Yer tutucu: saatler]",
    hoursNote: "Randevu ile.",
  },
  footer: {
    blurb: "Mannheim'da Almanca ve Türkçe hukuki danışmanlık.",
    navTitle: "Menü",
    areasTitle: "Hukuk Alanları",
    contactTitle: "İletişim",
    imprint: "Künye (Impressum)",
    privacy: "Gizlilik",
    copyright: "© 2026 Avukatlık Bürosu Meral Gören",
    callLink: "Telefon",
    waLink: "WhatsApp",
    formLink: "İletişim formu",
    route: "Yol tarifi",
  },
  partner: {
    label: "İş birliği",
    title: "Türk hukuku işleriniz, Mannheim'dan yürütülür.",
    text: "Boşanma, miras ve tanıma davaları çoğu zaman iki hukuk düzenini birden ilgilendirir. Türk hukukuna giren konularda Doğru Kanzlei ile birlikte çalışıyorum. Böylece işiniz tek elden yürür, bunun için Türkiye'ye gitmeniz gerekmez.",
    firm: "Doğru Kanzlei",
    person: "Avukat Hasan Doğru",
    bio: "Ankara Barosu'na ve § 207 BRAO uyarınca Karlsruhe Barosu'na kayıtlıdır. Mannheim Sulh Mahkemesi'nde Türk hukuku bilirkişisi olarak listelenmiştir.",
    locationsLabel: "Ofisler",
    locations: "Mannheim · Ankara",
    languagesLabel: "Diller",
    languages: "Türkçe · Deutsch · English",
    areasLabel: "Hangi konularda destek verir",
    areas: [
      "Alman mahkeme kararlarının Türkiye'de tanınması",
      "Boşanma ve aile hukuku",
      "Türkiye'deki miras işleri",
      "Türkiye'deki ceza davaları",
      "Vekâletname ve apostil",
    ],
    cta: "Doğru Kanzlei web sitesi",
  },
  cookie: {
    title: "Çerezler ve gizlilik",
    text: "Bu web sitesi teknik olarak gerekli çerezler kullanır. İstatistik amaçlı isteğe bağlı çerezler yalnızca onayınızla kullanılır (§ 25 TDDDG, GDPR md. 6).",
    acceptAll: "Tümünü kabul et",
    necessaryOnly: "Yalnızca gerekli",
    customize: "Özelleştir",
    save: "Seçimi kaydet",
    necessary: "Gerekli",
    necessaryText: "Sitenin çalışması için zorunludur.",
    stats: "İstatistik",
    statsText: "Siteyi iyileştirmek için anonim kullanım istatistiği.",
  },
  page: {
    home: "Ana Sayfa",
    more: "Devamını oku",
    allPosts: "Tüm yazılar",
    backHome: "Ana sayfaya dön",
    areaEyebrow: "Hukuk Alanları",
    areaTopics: "Tipik konular",
    areaHow: "Nasıl çalışıyorum",
    areaAside: "Konunuzu kısaca açıklayın – Almanca veya Türkçe.",
    otherAreas: "Diğer hukuk alanları",
    postDisclaimer:
      "Bu yazı genel bir bakış sunar ve somut olaydaki hukuki danışmanlığın yerine geçmez. Her zaman başvurunuz sırasındaki hukuki durum esas alınır.",
    legalNote:
      "Köşeli parantez içindeki tüm bilgiler yer tutucudur; yayından önce müvekkil tarafından tamamlanmalı ve hukuki olarak kontrol edilmelidir.",
    blog: {
      eyebrow: "Blog",
      title: "Yazılar",
      lead: "Kısa ve anlaşılır: medeni, iş, yabancılar, aile ve trafik hukukundan güncel sorular.",
    },
    danke: {
      eyebrow: "İletişim",
      title: "Talebiniz için teşekkürler",
      lead: "Mesajınız ulaştı.",
      body: "Belirttiğiniz iletişim kanalı üzerinden – e-posta veya telefon – en kısa sürede size dönüş yaparım.",
      urgent: "Acil durumlarda bana şu numaradan ulaşabilirsiniz:",
    },
    impressum: {
      eyebrow: "Hukuki bilgiler",
      title: "Künye (Impressum)",
      lead: "§ 5 DDG uyarınca bilgiler. Bağlayıcı sürüm Almancadır.",
      sections: [
        {
          heading: "Sağlayıcı",
          paragraphs: [
            "Rechtsanwaltskanzlei Meral Gören\nAvukat Meral Gören\nR1 2,3\n68161 Mannheim\nAlmanya",
          ],
        },
        {
          heading: "İletişim",
          paragraphs: ["Telefon: +49 176 31186560\nE-posta: [Yer tutucu]"],
        },
        {
          heading: "Meslek unvanı ve baro",
          paragraphs: [
            "Meslek unvanı: Rechtsanwältin (Almanya Federal Cumhuriyeti)\nYetkili baro: [Yer tutucu]",
          ],
        },
        {
          heading: "Mesleki düzenlemeler",
          paragraphs: ["BRAO, BORA, FAO, RVG, CCBE meslek kuralları – www.brak.de adresinde."],
        },
        {
          heading: "Mesleki sorumluluk sigortası",
          paragraphs: ["[Yer tutucu: sigortacı, adres, geçerlilik alanı]"],
        },
        {
          heading: "KDV kimlik numarası",
          paragraphs: ["[Yer tutucu]"],
        },
      ],
    },
    datenschutz: {
      eyebrow: "Hukuki bilgiler",
      title: "Gizlilik Politikası",
      lead: "GDPR md. 13 uyarınca kişisel verilerin işlenmesine ilişkin bilgiler. Bağlayıcı sürüm Almancadır.",
      sections: [
        {
          heading: "1. Sorumlu",
          paragraphs: [
            "Avukat Meral Gören, R1 2,3, 68161 Mannheim, Telefon +49 176 31186560, E-posta [Yer tutucu].",
          ],
        },
        {
          heading: "2. Barındırma ve sunucu kayıtları",
          paragraphs: [
            "Siteye erişimde barındırma sağlayıcısı [Yer tutucu] IP adresi, zaman, açılan sayfa ve tarayıcı bilgilerini otomatik işler. Hukuki dayanak: GDPR md. 6/1-f.",
          ],
        },
        {
          heading: "3. İletişim formu ve e-posta",
          paragraphs: [
            "Formdaki bilgiler (ad, e-posta, telefon, hukuk alanı, mesaj) talebinizin işlenmesi için kullanılır ve e-posta ile büroya iletilir. Hukuki dayanak: GDPR md. 6/1-b ve onayınız (1-a). Vekâlet verilmez ve saklama yükümlülüğü yoksa talep sonrasında silinir.",
          ],
        },
        {
          heading: "4. WhatsApp",
          paragraphs: [
            "WhatsApp üzerinden iletişimde WhatsApp Ireland Ltd. verilerinizi kendi kurallarına göre işler. Lütfen gizli dosya içeriklerini WhatsApp'tan göndermeyin.",
          ],
        },
        {
          heading: "5. Çerezler",
          paragraphs: [
            "Teknik olarak gerekli çerezler § 25/2 TDDDG uyarınca kullanılır. İsteğe bağlı istatistik çerezleri yalnızca onayınızla (§ 25/1 TDDDG, GDPR md. 6/1-a). Seçiminizi çerez bildirimi üzerinden değiştirebilirsiniz. [Yer tutucu: kullanılan hizmetler]",
          ],
        },
        {
          heading: "6. Haklarınız",
          paragraphs: [
            "Erişim, düzeltme, silme, işlemenin kısıtlanması, veri taşınabilirliği ve itiraz hakkına (GDPR md. 15–21) ve bir denetim makamına şikâyet hakkına sahipsiniz.",
          ],
        },
      ],
    },
  },
};
